### ISSUE TITLE
Support other imagemin plugins

### ISSUE THREAD

**Issue by teddybradford** [stawberri/imagemin-brunch#1]
It would be really awesome to have options for adding other imagemin plugins like imagemin-mozjpeg.

**Comment by stawberri** [comment]
I'll look into this. I'd like to keep it as low-configuration as brunch is, so I'll see if I can auto-detect installed plugins that start with `imagemin-` and enable them without requiring you to change your config file.

**Comment by stawberri** [comment]
I ended up adding it as an option instead of using my auto-detect idea.

**Comment by teddybradford** [comment]
Awesome! Thanks! 👍
