### ISSUE TITLE
Image minification failed due to First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by jgauna** [stawberri/imagemin-brunch#3]
Hey, can't figure out this issue with brunch. Any help?

**Comment by stawberri** [comment]
Sorry, I mainly use React now so I haven't needed this plugin for a while. Maybe something changed about Brunch or imagemin that broke it. 😥

**Comment by jgauna** [comment]
I've moved to ```imageoptmizer-brunch``` which works fine with this config

```
    imageoptimizer: {
      smushit: true,
      path: 'app/assets/img'
    }
```
